version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
  allow-serial-runners: true
  relative-path-mode: gomod
output:
  formats:
    text:
      path: stderr
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - file
    - severity
    - linter
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    # - unused
    - bodyclose
    - copyloopvar
    - errorlint
    - exhaustive
    - gocritic
    - gocyclo
    - sloglint
    - loggercheck
    - nestif
    # Inspects source code for security problems.
    - gosec
    # Check whether the function uses a non-inherited context.
    - contextcheck
    # Finds sending http request without context.Context.
    - noctx
    # Checks that fmt.Sprintf can be replaced with a faster alternative
    - perfsprint
    # check sql code
    - rowserrcheck
    - sqlclosecheck
    - testifylint
    # Remove unnecessary type conversions
    - unconvert
    # A linter that detect the possibility to use variables/constants from the Go standard library
    - usestdlibvars
    # Reports uses of functions with replacement inside the testing package
    - usetesting
    # Checks that errors returned from external packages are wrapped
    - wrapcheck
    # Finds repeated strings that could be replaced by a constant.
    - goconst
    # Finds the code that returns nil even if it checks that the error is not nil.
    - nilerr
    - nilnil
    - prealloc
    - promlinter
    - revive
  settings:
    gocyclo:
      min-complexity: 10
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
